name:"Deploy para VPS"
on: 
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v1
        with:
          host: "69.62.94.212"
          username: "root"
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/sistema"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1
        with:
          host: "69.62.94.212"
          username: root
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /sistema
            composert install --no-dev --no-progress -a
            
    
